### ISSUE TITLE
Increase standalone default configuration

### ISSUE THREAD

**Issue by BFergerson** [sourceplusplus/probe-jvm#48]
```yml
skywalking:
  agent:
    is_cache_enhanced_class: true
    class_cache_mode: "FILE"
  plugin:
    toolkit:
      log:
        transmit_formatted: false
```

---

Would need to add notes in the documentation that these settings are necessary/recommended for non-standalone.
